# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: COBOL / Test (Windows)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache GnuCOBOL
        id: cache-gnu-cobol
        uses: actions/cache@v3
        with:
          path: ~\gnu-cobol-3.1.2.7z
          key: ${{ runner.os }}-gnu-cobol-3.1.2

      - name: Download GnuCOBOL
        if: steps.cache-gnu-cobol.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $requestOpts = @{
            Headers           = If ($env:GITHUB_TOKEN) { @{ Authorization = "Bearer ${env:GITHUB_TOKEN}" } } Else { @{ } }
            MaximumRetryCount = 3
            RetryIntervalSec  = 1
          }
          Invoke-WebRequest -Uri 'https://arnoldtrembley.com/GC312-BDB-M64-rename-7z-to-exe.7z' -OutFile ~\gnu-cobol-3.1.2.7z @requestOpts

      - name: Extract GnuCOBOL
        shell: pwsh
        run: 7z x ~\gnu-cobol-3.1.2.7z -ognucobol

      - name: Run tests for all exercises
        shell: pwsh
        run: |
          $env:Path = "D:\a\cobol\cobol\gnucobol\bin;" + $env:Path
          [System.Environment]::SetEnvironmentVariable('COB_CONFIG_DIR', 'D:\a\cobol\cobol\gnucobol\config')
          [System.Environment]::SetEnvironmentVariable('COB_COPY_DIR', 'D:\a\cobol\cobol\gnucobol\copy')
          [System.Environment]::SetEnvironmentVariable('COB_CFLAGS', '-I D:\a\cobol\cobol\gnucobol\include')
          [System.Environment]::SetEnvironmentVariable('COB_LDFLAGS', '-L D:\a\cobol\cobol\gnucobol\lib')
          [System.Environment]::SetEnvironmentVariable('COB_LIBRARY_PATH', 'D:\a\cobol\cobol\gnucobol\lib')
          [System.Environment]::SetEnvironmentVariable('COB_LIBS', 'D:\a\cobol\cobol\gnucobol\bin\libcob-4.dll')
          bin/test.ps1
